import test from 'node:test';import assert from 'node:assert/strict';import {createHash}from'node:crypto';import {mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
import{createStore,stableId}from'../src/store.mjs';import{createIntelligence}from'../src/intelligence.mjs';import{createIntelligenceStore}from'../src/intelligence-store.mjs';import{createPublicCatalogue,enrichPublicCatalogue}from'../src/public-catalogue.mjs';
import{GRAPHQL_SOURCE_URL,README_PATHS,githubReadmeQuery,verifyGraphqlSource,graphqlReadme,isPublicCensusSearch}from'../src/github-graphql-source.mjs';import{createCensusImporter}from'../scripts/lib/github-census-import.mjs';import{retainGraphqlReadmes}from'../scripts/lib/github-graphql-hydrate.mjs';
import{createDiscovery}from'../src/discovery.mjs';import{repositoryReadmeRefs}from'../src/github-readme.mjs';
const hash=(x,a='sha256')=>createHash(a).update(x).digest('hex'),revision='a'.repeat(40),stamp='2026-10-01T00:00:00.000Z';
const repos=['example/alpha','example/beta'];
function response(){const data={};for(const [i,repo]of repos.entries()){const text=i?'# Beta\n\nFOREIGN_BETA_ONLY archive management.':'# Alpha\n\nTARGET_ALPHA_ONLY edits documents with shared review.\n\n## Features\n- Track changes and comments.';const bytes=Buffer.from(text),oid=hash(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes]),'sha1');data['r'+i]={databaseId:i+1,nameWithOwner:repo,isPrivate:false,defaultBranchRef:{target:{oid:revision,...Object.fromEntries(README_PATHS.map((_,j)=>['f'+j,null])),f0:{path:'README.md',oid,object:{oid,byteSize:bytes.length,isBinary:false,isTruncated:false,text}}}}};}data.rateLimit={cost:1,remaining:4998,resetAt:stamp};return{data};}
function snapshot(data=response(),query=githubReadmeQuery(repos)){const body=JSON.stringify(data),sha256=hash(body),request={method:'POST',body:JSON.stringify({query})};return{url:GRAPHQL_SOURCE_URL,body,sha256,id:stableId(`${GRAPHQL_SOURCE_URL}\n${sha256}`),status:200,contentType:'application/json',fetchedAt:stamp,lastFetchedAt:stamp,request,requestSha256:hash(request.body)};}
function metadata(){const url='https://api.github.com/search/repositories?'+new URLSearchParams({q:'is:public fork:true stars:>=1000',sort:'stars',order:'desc',per_page:'100',page:'1'});const items=repos.map((r,i)=>({id:i+1,full_name:r,name:r.split('/')[1],html_url:'https://github.com/'+r,description:'Source-backed product metadata',private:false,fork:false,archived:false,disabled:false,topics:['document'],stargazers_count:90000,default_branch:'main',license:null}));const body=JSON.stringify({items,total_count:2,incomplete_results:false});return{url,body,sha256:hash(body),status:200,contentType:'application/json',fetchedAt:stamp};}
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'glasses-gql-')),store=createStore(dir);t.after(async()=>{store.close();await rm(dir,{recursive:true,force:true});});const source=metadata(),admit=createCensusImporter({store}),items=repos.map((repository,i)=>admit({repository,repositoryId:i+1,url:'https://github.com/'+repository,stars:90000,sourceHash:source.sha256},source).item);return{store,dir,items,source};}
test('new census rows have complete observed metrics and repeated startup performs no source reads or backfill writes',async t=>{
 const f=await fixture(t),s=snapshot();retainGraphqlReadmes({store:f.store,snapshot:s,expected:f.items.map((item,index)=>({id:item.id,repository:repos[index],repositoryId:index+1}))});
 const before=f.items.map(item=>f.store.getCapability(item.id));
 for(const item of before){assert.equal(item.github.starsFetchedAt,stamp);assert.equal(item.github.starsObservedAt,stamp);assert.equal(item.github.fork,false);assert.equal(item.github.disabled,false);}
 let reads=0,writes=0;const spy={...f.store,getEvidence(...args){reads++;return f.store.getEvidence(...args);},upsertCapability(...args){writes++;return f.store.upsertCapability(...args);}};
 for(let startup=0;startup<2;startup++)createDiscovery({store:spy,fetcher:async()=>{throw Error('Startup must not fetch source');}});
 assert.equal(reads,0);assert.equal(writes,0);assert.deepEqual(f.items.map(item=>f.store.getCapability(item.id)),before);
});
test('bounded reviewed query binds exact aliases, public numeric identities, immutable commits and Git blob bytes',()=>{const s=snapshot(),batch=verifyGraphqlSource(s);assert.equal(batch.records.length,2);const row=batch.records[0],file=row.files[0];assert.match(file.text,/TARGET_ALPHA_ONLY/);const proof={evidenceId:s.id,sha256:s.sha256,alias:'r0',repositoryId:1,repository:repos[0],revision,path:file.path,blobOid:file.blobOid};assert.equal(graphqlReadme(s,proof).text,file.text);assert.throws(()=>graphqlReadme(s,{...proof,alias:'r1'}),/different repository/);assert.throws(()=>githubReadmeQuery(Array(51).fill('owner/repo')),/bounded/);assert.throws(()=>githubReadmeQuery(['owner/repo"}) mutation{']));});
test('private, changed names/IDs, wrong file paths, byte sizes, OIDs and unknown aliases fail closed',()=>{for(const [label,change]of[
 ['private',d=>d.data.r1.isPrivate=true],['name',d=>d.data.r0.nameWithOwner='elsewhere/alpha'],['duplicate ID',d=>d.data.r1.databaseId=1],['commit',d=>d.data.r0.defaultBranchRef.target.oid='main'],['path',d=>d.data.r0.defaultBranchRef.target.f0.path='private.txt'],['oid',d=>d.data.r0.defaultBranchRef.target.f0.object.oid='b'.repeat(40)],['alias',d=>d.data.other=d.data.r0],['errors',d=>d.errors=[{message:'upstream rejected'}]],
 ]){const data=response();change(data);assert.throws(()=>verifyGraphqlSource(snapshot(data)),undefined,label);}
 const s=snapshot();assert.throws(()=>verifyGraphqlSource({...s,requestSha256:'0'.repeat(64)}));assert.throws(()=>verifyGraphqlSource(snapshot(response(),githubReadmeQuery(repos)+' mutation{bad}')));assert.throws(()=>verifyGraphqlSource({...s,body:s.body+' '}));
});
test('binary and truncated README declarations stay explicit unavailable rather than supplying partial text',()=>{for(const field of ['isBinary','isTruncated']){const data=response();data.data.r0.defaultBranchRef.target.f0.object[field]=true;const result=verifyGraphqlSource(snapshot(data)).records[0];assert.equal(result.status,'no-supported-readme');assert.equal(result.files.length,0);assert.equal(result.rejected.length,1);}});
test('a README directory has no Blob fragment and cannot replace the verified text file',()=>{const data=response();data.data.r0.defaultBranchRef.target.f3={path:'README',oid:'b'.repeat(40),object:{}};const result=verifyGraphqlSource(snapshot(data)).records[0];assert.equal(result.files.length,1);assert.equal(result.rejected[0].path,'README');assert.match(result.rejected[0].reason,/not a Blob/);});
test('lossy or mismatching text never becomes source; verified sibling repositories remain usable',()=>{for(const mutate of [file=>file.object.byteSize++,file=>file.object.text+='tamper']){const data=response();mutate(data.data.r0.defaultBranchRef.target.f0);const s=snapshot(data),batch=verifyGraphqlSource(s);assert.equal(batch.records[0].files.length,0);assert.equal(batch.records[0].status,'no-supported-readme');assert.match(batch.records[0].rejected[0].reason,/Git blob/);assert.equal(batch.records[1].files.length,1);assert.throws(()=>graphqlReadme(s,{evidenceId:s.id,sha256:s.sha256,alias:'r0',repositoryId:1,repository:repos[0],revision,path:'README.md',blobOid:data.data.r0.defaultBranchRef.target.f0.oid}));}});
test('a later REST refresh clears the active GraphQL binding but retains its historical proof',async t=>{const f=await fixture(t),s=snapshot(),expected=f.items.map((x,i)=>({id:x.id,repository:repos[i],repositoryId:i+1}));retainGraphqlReadmes({store:f.store,snapshot:s,expected});const before=f.store.getCapability(f.items[0].id),nextRevision='b'.repeat(40),discovery=createDiscovery({store:f.store,fetcher:async url=>{let data;if(url==='https://api.github.com/repos/'+repos[0])data=JSON.parse(f.source.body).items[0];else if(url.includes('/commits/'))data={sha:nextRevision};else if(url.includes('/readme?'))data={path:'README.adoc',encoding:'base64',content:Buffer.from('New immutable README body').toString('base64')};else throw Object.assign(Error('No licence fixture'),{status:404});const body=JSON.stringify(data);return{url,body,status:200,sha256:hash(body),contentType:'application/json',fetchedAt:stamp};}});const after=await discovery.inspect(before.id,{fetchSource:true,refreshSource:true});assert.equal(after.graphqlReadmeProof,null);assert.deepEqual(after.sourceHistory.at(-1).previousGraphqlReadmeProof,before.graphqlReadmeProof);assert.ok(!repositoryReadmeRefs(after).includes(before.graphqlReadmeProof.evidenceId));assert.equal(after.provenance.resolvedRevision,nextRevision);});
test('census refresh updates same-identity upstream fields and stars, preserving explicit local fields and retained source',async t=>{const f=await fixture(t),old=f.store.upsertCapability({...f.items[0],name:'Private local title',tags:['local'],repositoryFiles:[{path:'README.md',content:'Keep exact source'}]}).item,admit=createCensusImporter({store:f.store}),next=structuredClone(f.source),data=JSON.parse(next.body);data.items[0].stargazers_count=91000;data.items[0].description='New upstream source description';data.items[0].topics=['new-topic'];next.body=JSON.stringify(data);next.sha256=hash(next.body);const row={repository:repos[0],repositoryId:1,url:old.url,stars:91000,sourceHash:next.sha256},result=admit(row,next).item;assert.equal(result.name,'Private local title');assert.deepEqual(result.tags,['local']);assert.equal(result.description,'New upstream source description');assert.equal(result.github.stars,91000);assert.equal(result.metadataEvidence.sha256,next.sha256);assert.deepEqual(result.repositoryFiles,old.repositoryFiles);const wrong=structuredClone(next),changed=JSON.parse(wrong.body);changed.items[0].id=999;wrong.body=JSON.stringify(changed);wrong.sha256=hash(wrong.body);assert.throws(()=>admit({...row,repositoryId:999,sourceHash:wrong.sha256},wrong),/numeric repository identity/);});
test('actual GitHub missing optional file errors are accepted only at exact null requested aliases',()=>{const data=response();const error={type:'NOT_FOUND',path:['r0','defaultBranchRef','target','f1'],message:"Could not resolve file for path 'readme.md'."};data.errors=[error];assert.equal(verifyGraphqlSource(snapshot(data)).records[0].files.length,1);for(const change of [e=>e.path[0]='r9',e=>e.path[3]='f0',e=>e.type='FORBIDDEN',e=>e.message="Could not resolve file for path 'secret.txt'.",e=>e.path.pop()]){const next=structuredClone(data);change(next.errors[0]);assert.throws(()=>verifyGraphqlSource(snapshot(next)));}});
test('cached batch validation remains bound to every source/request value and freezes returned proof',()=>{const s=snapshot(),value=verifyGraphqlSource(s);assert.equal(verifyGraphqlSource(structuredClone(s)),value);assert.throws(()=>{value.records[0].repository='foreign/repo';});for(const change of [x=>x.body+=' ',x=>x.request.body+=' ',x=>x.request.method='GET',x=>x.status=201,x=>x.url+='?private',x=>x.id='0'.repeat(20),x=>x.requestSha256='0'.repeat(64)]){const changed=structuredClone(s);change(changed);assert.throws(()=>verifyGraphqlSource(changed));}assert.equal(verifyGraphqlSource(s),value);});
test('replaying an applied exact source batch is idempotent and preserves source history',async t=>{const f=await fixture(t),s=snapshot(),expected=f.items.map((x,i)=>({id:x.id,repository:repos[i],repositoryId:i+1}));retainGraphqlReadmes({store:f.store,snapshot:s,expected});const before=f.store.getCapability(f.items[0].id);const result=retainGraphqlReadmes({store:f.store,snapshot:s,expected});assert.ok(result.items.every(x=>x.reused));assert.deepEqual(f.store.getCapability(f.items[0].id),before);});
test('request receipts cannot overwrite existing response binding, and summaries omit the body',async t=>{const f=await fixture(t),s=snapshot(),ref=f.store.retainEvidence(s);assert.equal(ref.request,undefined);assert.equal(f.store.getEvidence(ref.id).request.body,s.request.body);assert.throws(()=>f.store.retainEvidence({...s,request:{method:'POST',body:s.request.body+' '}}),/different request/);assert.throws(()=>f.store.retainEvidence({...s,url:'https://api.github.com/other'}),/request receipt/);assert.ok(f.store.evidence().every(x=>x.request===undefined));});
test('zero-network census admission validates exact retained numeric source and preserves existing local overlays',async t=>{const f=await fixture(t),admit=createCensusImporter({store:f.store}),old=f.store.upsertCapability({...f.items[0],name:'Private local title',tags:['local'],sourceFiles:[{path:'keep.txt',content:'keep'}]}).item;const row={repository:repos[0],repositoryId:1,url:old.url,stars:90000,sourceHash:f.source.sha256};const again=admit(row,f.source);assert.equal(again.preservedExisting,true);assert.equal(f.store.getCapability(old.id).name,'Private local title');assert.equal(f.store.getCapability(old.id).sourceFiles[0].content,'keep');assert.throws(()=>admit({...row,repositoryId:2},f.source),/differs/);assert.throws(()=>admit({...row,stars:1},f.source),/differs/);assert.equal(isPublicCensusSearch(f.source.url),true);assert.equal(isPublicCensusSearch(f.source.url.replace('is%3Apublic','customerSecret')),false);});
test('hydration/classifier/public projection use only the owned README and preserve private state',async t=>{const f=await fixture(t),s=snapshot(),expected=f.items.map((x,i)=>({id:x.id,repository:repos[i],repositoryId:i+1}));const report=retainGraphqlReadmes({store:f.store,snapshot:s,expected});assert.equal(report.items.filter(x=>x.readmePinned).length,2);const calls=[];const providers={status:async()=>({jev:{configured:true,model:'jev-1.13.0'}}),classify:async(provider,input)=>{calls.push(input);return{model:'jev-1.13.0',results:input.cards.map(card=>({id:card.id,artifact:'whole-product',adoption:'deploy-service',capabilities:['document editing'],confidence:.8,evidenceIds:card.evidenceIds})),usage:{inputTokens:10,outputTokens:5}};},plan:async()=>{},rank:async()=>{}};const engine=createIntelligence({store:f.store,dataDir:f.dir,discovery:{inspect:async()=>{throw Error('Unexpected source refetch');}},providers});try{const job=engine.enqueue({type:'classify',provider:'jev',candidateIds:[f.items[0].id]});for(let i=0;i<200&&['running','queued'].includes(engine.getJob(job.id).status);i++)await new Promise(r=>setTimeout(r,5));assert.equal(engine.getJob(job.id).status,'completed',JSON.stringify(engine.getJob(job.id).errors));assert.match(JSON.stringify(calls[0]),/TARGET_ALPHA_ONLY/);assert.doesNotMatch(JSON.stringify(calls[0]),/FOREIGN_BETA_ONLY/);const db=createIntelligenceStore(f.dir);const assessment=db.get('assessments',f.items[0].id);db.close();const caps=f.items.map(x=>f.store.getCapability(x.id)),evidence=f.store.evidence().map(x=>f.store.getEvidence(x.id));const pub=createPublicCatalogue({capabilities:caps,evidence,assessments:[assessment]});assert.ok(pub.snapshot.items.find(x=>x.id===f.items[0].id).assessment);const rich=enrichPublicCatalogue(pub.snapshot,{evidence});assert.match(rich.items.find(x=>x.id===f.items[0].id).details.overview,/TARGETALPHAONLY/);assert.doesNotMatch(JSON.stringify(rich.items.find(x=>x.id===f.items[0].id)),/FOREIGN_BETA_ONLY/);const wrong=caps.map(x=>x.id===f.items[0].id?{...x,graphqlReadmeProof:caps[1].graphqlReadmeProof}:x);assert.equal(createPublicCatalogue({capabilities:wrong,evidence,assessments:[assessment]}).snapshot.items.find(x=>x.id===f.items[0].id).assessment,null);}finally{await engine.close();}});

