import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createStore} from '../src/store.mjs';
import {GRAPHQL_SOURCE_URL,README_PATHS,githubReadmeQuery} from '../src/github-graphql-source.mjs';
import {createCensusImporter} from '../scripts/lib/github-census-import.mjs';
import {pinnedFallbackIdentity,retainPinnedReadmeFallback} from '../scripts/lib/github-pinned-readme-fallback.mjs';
import {createPublicCatalogue,enrichPublicCatalogue} from '../src/public-catalogue.mjs';
const hash=(value,a='sha256')=>createHash(a).update(value).digest('hex'),repository='sample/project',revision='a'.repeat(40),at='2026-10-01T00:00:00Z';
const document=(url,data,status=200)=>{const body=typeof data==='string'?data:JSON.stringify(data);return{url,body,sha256:hash(body),status,contentType:'application/json',fetchedAt:at};};
function graphql(){const request={method:'POST',body:JSON.stringify({query:githubReadmeQuery([repository])})};return{...document(GRAPHQL_SOURCE_URL,{data:{r0:{databaseId:12,nameWithOwner:repository,isPrivate:false,defaultBranchRef:{target:{oid:revision,...Object.fromEntries(README_PATHS.map((_,i)=>['f'+i,null]))}}},rateLimit:{cost:1,remaining:4999,resetAt:at}}}),request,requestSha256:hash(request.body)};}
function readme(text='# Project\n\nA document editor with shared review.',encoding='base64'){const bytes=Buffer.from(text),sha=hash(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes]),'sha1');return document('https://api.github.com/repos/'+repository+'/readme?ref='+revision,{path:'README.adoc',sha,size:bytes.length,encoding,content:encoding==='base64'?bytes.toString('base64'):'',download_url:'https://raw.githubusercontent.com/'+repository+'/'+revision+'/README.adoc'});}
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'pinned-readme-')),store=createStore(dir);t.after(async()=>{store.close();await rm(dir,{recursive:true,force:true});});const metadata=document('https://api.github.com/search/repositories?'+new URLSearchParams({q:'is:public fork:true stars:>=1000',sort:'stars',order:'desc',per_page:'100',page:'1'}),{total_count:1,incomplete_results:false,items:[{id:12,full_name:repository,html_url:'https://github.com/'+repository,name:'project',description:'Document editor',private:false,fork:false,archived:false,disabled:false,topics:[],stargazers_count:1500,default_branch:'main',license:null}]});const row={repository,repositoryId:12,url:'https://github.com/'+repository,stars:1500,sourceHash:metadata.sha256},item=createCensusImporter({store})(row,metadata).item;return{store,row:{...row,id:item.id,metadataSourceHash:metadata.sha256},commitSnapshot:graphql(),response:readme()};}
test('one pinned response retains exact source and public details without changing private overlays or metadata',async t=>{const f=await fixture(t),before=f.store.getCapability(f.row.id);f.store.upsertCapability({...before,name:'My private name',tags:['my-local-tag'],notes:'Keep me',sourceFiles:[{path:'private-note',content:'keep'}]});const result=retainPinnedReadmeFallback(f),after=f.store.getCapability(f.row.id);assert.equal(result.readmePinned,true);assert.equal(after.name,'My private name');assert.deepEqual(after.tags,['my-local-tag']);assert.equal(after.notes,'Keep me');assert.deepEqual(after.sourceFiles,[{path:'private-note',content:'keep'}]);assert.deepEqual(after.metadataEvidence,before.metadataEvidence);assert.equal(after.provenance.resolvedRevision,revision);assert.equal(result.proof.evidence.length,1);assert.equal(after.repositoryFiles[0].path,'README.adoc');const evidence=f.store.evidence().map(ref=>f.store.getEvidence(ref.id));const pack=createPublicCatalogue({capabilities:[after],evidence}).snapshot;assert.match(enrichPublicCatalogue(pack,{evidence}).items[0].details.overview,/document editor/i);});
test('foreign numeric identity, request/query, changed metadata and source bytes fail before any write',async t=>{const f=await fixture(t),before=f.store.getCapability(f.row.id),count=f.store.evidence().length;for(const changed of [{row:{...f.row,repositoryId:99}},{row:{...f.row,repository:'other/project'}},{row:{...f.row,metadataSourceHash:'0'.repeat(64)}},{response:{...f.response,url:f.response.url.replace(repository,'other/project')}},{response:{...f.response,body:f.response.body+' '}},{commitSnapshot:{...f.commitSnapshot,requestSha256:'0'.repeat(64)}},{response:document(f.response.url,{...JSON.parse(f.response.body),size:99999})}])assert.throws(()=>retainPinnedReadmeFallback({...f,...changed}));assert.deepEqual(f.store.getCapability(f.row.id),before);assert.equal(f.store.evidence().length,count);});
test('verified omitted inline content needs exact declared raw bytes, never arbitrary raw source',async t=>{const f=await fixture(t),text='# Project\n\nA document editor with shared review.';f.response=readme(text,'none');const raw=document(JSON.parse(f.response.body).download_url,text);assert.throws(()=>retainPinnedReadmeFallback({...f,rawResponse:{...raw,url:raw.url.replace(repository,'other/project')}}));const result=retainPinnedReadmeFallback({...f,rawResponse:raw});assert.equal(result.readmePinned,true);assert.equal(result.proof.evidence[0].url,raw.url);assert.equal(f.store.getCapability(f.row.id).repositoryReadmeProof.apiEvidence.sha256,f.response.sha256);});
test('pinned404 records actual absence and never invents readable source',async t=>{const f=await fixture(t);f.response=document(f.response.url,{message:'Not Found'},404);const result=retainPinnedReadmeFallback(f),item=f.store.getCapability(f.row.id);assert.equal(result.readmePinned,false);assert.equal(item.repositoryFiles.length,0);assert.equal(item.provenance.resolvedRevision,revision);assert.equal(item.sourceState.errors[0].url,f.response.url);assert.match(item.sourceState.errors[0].error,/HTTP 404/);assert.equal(f.store.getEvidence(item.repositoryEvidence[0].id).status,404);});
test('rate, auth and transient failures are not source absence and do not mutate the row',async t=>{const f=await fixture(t),before=f.store.getCapability(f.row.id);for(const status of [401,403,429,500,502,504])assert.throws(()=>retainPinnedReadmeFallback({...f,response:document(f.response.url,{message:'failure'},status)}));assert.deepEqual(f.store.getCapability(f.row.id),before);});

test('intact pinned non-UTF8 base64 is retained as unsupported without raw fetch or invented text',async t=>{
 const f=await fixture(t),bytes=Buffer.from([0x61,0xff,0x62]),data=JSON.parse(f.response.body);
 Object.assign(data,{content:bytes.toString('base64'),size:bytes.length,sha:hash(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes]),'sha1')});f.response=document(f.response.url,data);
 const result=retainPinnedReadmeFallback(f),item=f.store.getCapability(f.row.id);
 assert.equal(result.readmePinned,false);assert.equal(result.unsupportedReadme.sha256,hash(bytes));assert.equal(result.unsupportedReadme.losslessUtf8,false);assert.match(result.error,/not lossless UTF-8/);assert.deepEqual(item.repositoryFiles,[]);assert.equal(item.repositoryReadmeProof,null);assert.equal(item.sourceState.errors[0].url,f.response.url);assert.equal(item.sourceState.errors[0].status,'unsupported');assert.equal(f.store.getEvidence(result.unsupportedReadme.declaration.id).body,f.response.body);
});

test('unsupported encoding requires exact bytes and pinned identity, not a decoder error alone',async t=>{
 const f=await fixture(t),bytes=Buffer.from([0x61,0xff,0x62]),data=JSON.parse(f.response.body);Object.assign(data,{content:bytes.toString('base64'),size:bytes.length,sha:hash(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes]),'sha1')});
 const before=f.store.getCapability(f.row.id);for(const altered of [{...data,size:4},{...data,sha:'0'.repeat(40)},{...data,content:Buffer.from('different').toString('base64')},{...data,download_url:data.download_url.replace(repository,'other/repo')},{...data,download_url:data.download_url.replace(revision,'main')}])assert.throws(()=>retainPinnedReadmeFallback({...f,response:document(f.response.url,altered)}));assert.deepEqual(f.store.getCapability(f.row.id),before);
});

test('exact native raw bytes can prove unsupported encoding when API base64 was re-encoded',async t=>{
 const f=await fixture(t),bytes=Buffer.from([0x61,0xff,0x62]),data=JSON.parse(f.response.body);Object.assign(data,{content:Buffer.from(bytes.toString('utf8')).toString('base64'),size:bytes.length,sha:hash(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes]),'sha1')});f.response=document(f.response.url,data);
 const rawBytes={url:data.download_url,status:200,bodyBase64:bytes.toString('base64'),sha256:hash(bytes)},before=f.store.getCapability(f.row.id);
 for(const bad of [{...rawBytes,status:404},{...rawBytes,url:rawBytes.url.replace(repository,'other/repo')},{...rawBytes,sha256:'0'.repeat(64)},{...rawBytes,bodyBase64:Buffer.from('wrong').toString('base64')}])assert.throws(()=>retainPinnedReadmeFallback({...f,rawBytes:bad}));assert.deepEqual(f.store.getCapability(f.row.id),before);
 const result=retainPinnedReadmeFallback({...f,rawBytes});assert.equal(result.readmePinned,false);assert.equal(result.unsupportedReadme.kind,'verified-pinned-non-utf8-raw');assert.equal(result.unsupportedReadme.sha256,hash(bytes));
});
test('older licence proof is retained as historical, never inherited onto another revision',async t=>{const f=await fixture(t),item=f.store.getCapability(f.row.id),licence={status:'fetched',scope:'repository',revision:'b'.repeat(40),spdx:'MIT'};f.store.upsertCapability({...item,license:'MIT',licenseEvidence:licence});retainPinnedReadmeFallback(f);const after=f.store.getCapability(f.row.id);assert.equal(after.license,null);assert.equal(after.licenseEvidence.status,'unverified-current-source');assert.deepEqual(after.licenseEvidence.previous,licence);});
test('no-default-commit and successful original source are not eligible for this recovery path',()=>{for(const change of [data=>data.data.r0.defaultBranchRef=null,data=>{const text='readme',bytes=Buffer.from(text),oid=hash(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes]),'sha1');data.data.r0.defaultBranchRef.target.f0={path:'README.md',oid,object:{oid,byteSize:bytes.length,isBinary:false,isTruncated:false,text}};}]){const snapshot=graphql(),data=JSON.parse(snapshot.body);change(data);snapshot.body=JSON.stringify(data);snapshot.sha256=hash(snapshot.body);assert.throws(()=>pinnedFallbackIdentity(snapshot,{repository,repositoryId:12,url:'https://github.com/'+repository}));}});
