import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {chromium} from 'playwright';
import {startServer} from '../src/server.mjs';

const directory=await mkdtemp(join(tmpdir(),'glasses-intelligence-ui-'));
const evidence=resolve(process.env.GLASSES_EVIDENCE_DIR||'evidence/intelligence-2026-09-28/browser');await mkdir(evidence,{recursive:true});
const report={startedAt:new Date().toISOString(),result:'RUNNING',checks:[],limitations:['Synthetic provider adapters and public-source fixtures exercise the real HTTP, engine, SQLite and browser. No real credentials or billed inference are used.','The main application and its data are untouched.']};
let app,browser,page,token,keyConfigured=false,testFailure=false,mode='success',classifyCalls=0,planCalls=0;
const pageErrors=[],receivedKey=[];
const fixtureKey='synthetic-ui-key-not-a-real-secret';
const fakeProviders={
  async status(){return {codex:{available:true,authenticated:true,configured:true,version:'synthetic-test-version',authType:'chatgpt',model:'fixture-codex-v1'},jev:{configured:keyConfigured,model:'jev-1.13.0',storage:'session-only'}}},
  async saveJevKey(value){assert.equal(value,fixtureKey);receivedKey.push(true);keyConfigured=true;},
  async removeJevKey(){keyConfigured=false;},
  async test(provider){if(testFailure)throw new Error('Synthetic provider authentication failed; check the saved key.');return {ok:true,provider,model:provider==='jev'?'jev-1.13.0':'fixture-codex-v1',inference:false,usage:{inputTokens:0,outputTokens:0,costUsd:provider==='jev'?0:null}};},
  async classify(provider,{cards}){classifyCalls++;return {model:provider==='jev'?'jev-1.13.0':'fixture-codex-v1',usage:{inputTokens:100,outputTokens:8,costUsd:provider==='jev'?.00001:null},results:cards.map(card=>({id:card.id,artifact:card.name.includes('Spinner')?'component':'tool-library',adoption:card.name.includes('Spinner')?'adapt-source':'embed-package',capabilities:card.name.includes('Spinner')?['visual-feedback']:['memory-recall','memory-export'],confidence:.87,evidenceIds:card.evidenceIds.slice(0,1)}))};},
  async plan({query,signal}){planCalls++;if(mode==='fail')throw new Error('Synthetic provider quota exhausted.');if(mode==='wait')await new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(signal.reason||new Error('Cancelled')),{once:true})});return {model:'fixture-codex-v1',queries:[],urls:['https://example.org/intelligence-public-source'],usage:{inputTokens:50,outputTokens:10}};},
  async rank(provider,{cards}){return {model:provider==='jev'?'jev-1.13.0':'fixture-codex-v1',usage:{inputTokens:90,outputTokens:5,costUsd:provider==='jev'?.00001:null},results:cards.map((card,index)=>({id:card.id,score:.9-index*.1}))};},
};
async function fixtureFetcher(url){if(url==='https://example.org/intelligence-public-source')return {url,status:200,contentType:'text/html',body:'<!doctype html><title>Fixture public memory tool</title><meta name="description" content="Synthetic public memory library with recall and export."/><h1>Fixture public memory tool</h1><p>This public fixture supports memory recall and export.</p>'};throw new Error('Unexpected synthetic source URL');}
async function api(route,method='GET',body){const response=await fetch(app.url+route,{method,headers:{'Content-Type':'application/json','X-Glasses-Token':token},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();assert.ok(response.ok,JSON.stringify(result));return result;}
async function until(fn){const deadline=Date.now()+20000;while(Date.now()<deadline){const value=await fn();if(value)return value;await delay(100)}throw new Error('Expected state did not appear');}
async function check(name,fn){const start=Date.now();try{await fn();report.checks.push({name,result:'PASS',ms:Date.now()-start});console.log('PASS '+name);}catch(error){report.checks.push({name,result:'FAIL',error:error.message});throw error;}}
const nav=()=>page.getByRole('navigation',{name:'Site navigation'});
const jobs=async()=>(await api('/api/intelligence/jobs')).items;
const completed=job=>!['queued','running'].includes(job.status);

try{
  app=await startServer({port:0,dataDir:directory,autoScout:false,providers:fakeProviders,discoveryFetcher:fixtureFetcher});({token}=await(await fetch(app.url+'/api/session')).json());
  function candidate(name,url,kind){const saved=app.store.retainEvidence({url,body:name+' is a synthetic public candidate with retained evidence.',contentType:'text/plain'});return app.store.upsertCapability({url,name,description:name+' public evidence for classification.',kind,origin:'live',provider:'Synthetic public test source',metadataEvidence:{id:saved.id},provenance:{sourceEvidenceId:saved.id},license:null}).item;}
  const memory=candidate('Fixture memory library','https://example.org/memory-library','solution'),spinner=candidate('Fixture Spinner','https://example.org/spinner','component');
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});report.browserVersion=browser.version();page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',error=>pageErrors.push(error.message));await page.goto(app.url+'/#connections');
  await check('Connections shows real adapter status and conservative settings without creating a canvas',async()=>{
    await page.getByRole('heading',{name:'Connections',exact:true}).waitFor();await page.getByText('Signed in',{exact:true}).waitFor();await page.getByText('Key required',{exact:true}).waitFor();
    assert.equal((await api('/api/workspaces')).items.length,0);assert.equal(await page.getByRole('spinbutton',{name:'Candidates per job',exact:true}).inputValue(),'10');assert.equal(await page.getByRole('spinbutton',{name:'Jobs per day',exact:true}).inputValue(),'4');assert.equal(await page.getByRole('checkbox',{name:'Automatically classify newly discovered evidence',exact:true}).isChecked(),false);
  });
  await check('Jev key save clears the password and leaves no browser storage or response echo',async()=>{
    const field=page.getByLabel('Jev API key',{exact:true});await field.fill(fixtureKey);await page.getByRole('button',{name:'Save Jev key',exact:true}).click();await page.getByText('Key saved',{exact:true}).waitFor();assert.equal(await field.inputValue(),'');assert.equal(receivedKey.length,1);
    assert.equal((await page.locator('body').textContent()).includes(fixtureKey),false);assert.equal(JSON.stringify(await api('/api/intelligence')).includes(fixtureKey),false);
    assert.deepEqual(await page.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)})),{local:[],session:[]});
  });
  await check('Provider tests expose success and actionable failures without saving credentials in the page',async()=>{
    await page.getByRole('button',{name:'Test Codex',exact:true}).click();await page.getByRole('region',{name:'Codex connection'}).getByText('Connection test completed',{exact:true}).waitFor();
    testFailure=true;await page.getByRole('button',{name:'Test Jev connection',exact:true}).click();await page.getByText('Synthetic provider authentication failed; check the saved key.',{exact:true}).waitFor();testFailure=false;
    await page.getByRole('button',{name:'Test Jev connection',exact:true}).click();await page.getByRole('region',{name:'Jev connection'}).getByText('Connection test completed',{exact:true}).waitFor();await page.screenshot({path:join(evidence,'connections-tested.png'),fullPage:true});
  });
  await check('Provider choice, budgets and opt-ins persist while retaining separate billing explanations',async()=>{
    await page.getByRole('combobox',{name:'AI provider',exact:true}).selectOption('jev');await page.getByRole('spinbutton',{name:'Jobs per day',exact:true}).fill('20');await page.getByRole('spinbutton',{name:'Jev daily budget (USD)',exact:true}).fill('0.12');await page.getByRole('checkbox',{name:'Automatically classify newly discovered evidence',exact:true}).check();await page.getByRole('button',{name:'Save AI settings',exact:true}).click();
    await until(async()=>(await api('/api/intelligence')).settings.provider==='jev');await page.reload();await until(async()=>await page.getByRole('spinbutton',{name:'Jobs per day',exact:true}).inputValue()==='20');assert.equal(await page.getByRole('checkbox',{name:'Automatically classify newly discovered evidence',exact:true}).isChecked(),true);assert.equal(await page.getByRole('checkbox',{name:'Automatically research enabled plans with Codex',exact:true}).isChecked(),false);
    assert.match(await page.locator('.connection-card').first().textContent(),/account allowance/);assert.match(await page.locator('.connection-card').last().textContent(),/separate API billing/);
  });
  let classification;
  await check('Classification jobs expose progress, retained assessments and cached repeat work',async()=>{
    await nav().getByRole('button',{name:'Research',exact:true}).click();await page.getByRole('button',{name:'Classify existing catalogue',exact:true}).click();classification=await until(async()=>(await jobs()).find(job=>job.type==='classify'&&completed(job)));assert.equal(classification.status,'completed',JSON.stringify(classification.errors));assert.equal(classification.result.assessmentIds.length,2);
    const card=page.locator('[data-job-id="'+classification.id+'"]');await card.getByText('completed',{exact:true}).waitFor();await card.getByRole('button',{name:'Run again',exact:true}).click();const repeat=await until(async()=>(await jobs()).find(job=>job.id!==classification.id&&job.type==='classify'&&completed(job)));assert.equal(repeat.result.cacheHits,2);assert.equal(classifyCalls,1);await page.screenshot({path:join(evidence,'classification-jobs.png'),fullPage:true});
    await card.getByRole('button',{name:'View AI findings',exact:true}).click();await page.getByRole('button',{name:'Inspect Fixture memory library',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Inspect Coolify',exact:true}).count(),0);
  });
  await check('Artifact filters and evidence inspection keep inferred claims separate from unknown licence facts',async()=>{
    await page.getByRole('combobox',{name:'Catalogue artifact',exact:true}).selectOption('tool-library');await until(async()=>await page.getByRole('button',{name:'Inspect Fixture Spinner',exact:true}).count()===0);await page.getByRole('button',{name:'Inspect Fixture memory library',exact:true}).click();const assessment=page.getByRole('region',{name:'Candidate assessment'});await assessment.getByText('Model inference',{exact:true}).waitFor();await assessment.getByText('87%',{exact:true}).waitFor();
    await assessment.getByText('Classification evidence (1)',{exact:true}).click();await assessment.getByRole('button',{name:/Read evidence /}).click();await assessment.getByText(/is a synthetic public candidate with retained evidence/).waitFor();assert.equal((await api('/api/catalog/'+memory.id)).item.license,null);await page.screenshot({path:join(evidence,'inferred-classification-evidence.png'),fullPage:true});
  });
  await check('Human correction survives reload and changed source evidence is marked stale without rewriting facts',async()=>{
    await page.getByRole('button',{name:'Correct classification',exact:true}).click();await page.getByRole('combobox',{name:'Corrected artifact type',exact:true}).selectOption('agent-extension');await page.getByRole('combobox',{name:'Corrected adoption approach',exact:true}).selectOption('configure-agent');await page.getByRole('textbox',{name:'Classification correction notes',exact:true}).fill('Synthetic human review corrected product role.');await page.getByRole('button',{name:'Save classification correction',exact:true}).click();await page.getByText('Human correction',{exact:true}).waitFor();
    app.store.upsertCapability({...app.store.getCapability(memory.id),description:'Source evidence changed after classification.'});await page.reload();await page.getByRole('button',{name:'Inspect Fixture memory library',exact:true}).click();await page.getByRole('region',{name:'Candidate assessment'}).getByText('Needs refresh',{exact:true}).waitFor();await page.getByText('Source evidence or classification policy changed. Refresh classification to review the current assessment.',{exact:true}).waitFor();await page.getByText('Human correction',{exact:true}).waitFor();const assessment=(await api('/api/catalog/'+memory.id+'/assessment')).assessment;assert.equal(assessment.artifact,'agent-extension');assert.equal(assessment.stale,true);assert.equal((await api('/api/catalog/'+memory.id)).item.license,null);await page.screenshot({path:join(evidence,'corrected-stale-classification.png'),fullPage:true});
  });
  await check('Selected candidate can refresh its own classification while preserving the human correction',async()=>{
    const priorIds=new Set((await jobs()).map(job=>job.id));await page.getByRole('button',{name:'Refresh AI classification',exact:true}).click();const job=await until(async()=>(await jobs()).find(job=>!priorIds.has(job.id)&&completed(job)));assert.equal(job.status,'completed');assert.deepEqual(job.candidateIds,[memory.id]);assert.equal(job.provider,'jev');await page.getByRole('region',{name:'Candidate assessment'}).getByText('Current evidence',{exact:true}).waitFor();await page.getByText('Human correction',{exact:true}).waitFor();await page.getByRole('link',{name:'View AI job history',exact:true}).waitFor();const assessment=(await api('/api/catalog/'+memory.id+'/assessment')).assessment;assert.equal(assessment.artifact,'agent-extension');assert.equal(assessment.stale,false);await page.screenshot({path:join(evidence,'selected-candidate-classification.png'),fullPage:true});
  });
  await check('A saved plan starts AI research and links the actual newly fetched source',async()=>{
    const {plan}=await api('/api/research/plans','POST',{name:'AI memory plan',query:'public memory tools',enabled:false});await nav().getByRole('button',{name:'Research',exact:true}).click();await page.getByRole('button',{name:'Research AI memory plan with AI',exact:true}).click();const job=await until(async()=>(await jobs()).find(job=>job.planId===plan.id&&completed(job)));assert.equal(job.status,'completed');assert.ok(job.candidateIds.length);assert.equal(job.planSnapshot.enabled,false);assert.equal(job.result.plan.model,'fixture-codex-v1');const card=page.locator('[data-job-id="'+job.id+'"]');await card.getByRole('button',{name:'View AI findings',exact:true}).click();await page.getByRole('button',{name:'Inspect Fixture public memory tool',exact:true}).waitFor();
  });
  await check('Failed jobs expose errors and explicit retry completes without losing history',async()=>{
    await nav().getByRole('button',{name:'Research',exact:true}).click();mode='fail';await page.getByRole('textbox',{name:'AI research brief',exact:true}).fill('Synthetic quota failure');await page.getByRole('button',{name:'Research with AI',exact:true}).click();const failed=await until(async()=>(await jobs()).find(job=>job.query==='Synthetic quota failure'&&job.status==='failed'));const card=page.locator('[data-job-id="'+failed.id+'"]');await card.getByText('Synthetic provider quota exhausted.',{exact:true}).waitFor();mode='success';await card.getByRole('button',{name:'Retry job',exact:true}).click();await until(async()=>(await jobs()).some(job=>job.query==='Synthetic quota failure'&&job.id!==failed.id&&job.status==='completed'));assert.equal((await api('/api/intelligence/jobs/'+failed.id)).job.status,'failed');
  });
  await check('Running AI work can be cancelled with its final state and usage retained',async()=>{
    mode='wait';await page.getByRole('textbox',{name:'AI research brief',exact:true}).fill('Synthetic cancellable job');await page.getByRole('button',{name:'Research with AI',exact:true}).click();const running=await until(async()=>(await jobs()).find(job=>job.query==='Synthetic cancellable job'&&job.status==='running'));const card=page.locator('[data-job-id="'+running.id+'"]');await card.getByRole('button',{name:'Cancel job',exact:true}).click();await card.getByText('cancelled',{exact:true}).waitFor();assert.equal((await api('/api/intelligence/jobs/'+running.id)).job.status,'cancelled');mode='success';await page.screenshot({path:join(evidence,'ai-job-cancelled.png'),fullPage:true});
  });
  await check('Ranking a brief returns actual ordered catalogue candidates with scores',async()=>{
    await page.getByRole('textbox',{name:'AI research brief',exact:true}).fill('memory');await page.getByRole('button',{name:'Rank catalogue for brief',exact:true}).click();const ranked=await until(async()=>(await jobs()).find(job=>job.type==='rank'&&completed(job)));assert.equal(ranked.status,'completed');assert.ok(ranked.result.rankings.length);const card=page.locator('[data-job-id="'+ranked.id+'"]');await card.getByRole('button',{name:'View AI findings',exact:true}).click();await page.getByText(/AI ranking score:/).first().waitFor();const names=await page.locator('.capability-card>strong').allTextContents();const first=(await api('/api/catalog/'+ranked.result.rankings[0].id)).item;assert.equal(names[0],first.name);await page.screenshot({path:join(evidence,'ranked-findings.png'),fullPage:true});
  });
  await check('Connections and AI research navigation preserve the shared canvas draft',async()=>{
    const workspace=await api('/api/workspaces','POST',{title:'Intelligence navigation fixture',capabilityId:memory.id,source:'export default ()=> <h1>Shared canvas remains available</h1>'});await page.goto(app.url+'/#workbench/'+workspace.id);await page.frameLocator('iframe[title="Isolated component preview"]').getByRole('heading',{name:'Shared canvas remains available'}).waitFor();await page.getByRole('button',{name:'Properties',exact:true}).click();await page.getByRole('textbox',{name:'Workspace name',exact:true}).fill('Draft retained through Connections');await nav().getByRole('button',{name:'Connections',exact:true}).click();await page.getByRole('heading',{name:'Connections',exact:true}).waitFor();await nav().getByRole('button',{name:'Research',exact:true}).click();await page.getByRole('heading',{name:'Research',exact:true}).waitFor();await nav().getByRole('button',{name:/^Workbench/}).click();assert.equal(await page.getByRole('textbox',{name:'Workspace name',exact:true}).inputValue(),'Draft retained through Connections');assert.equal((await api('/api/workspaces/'+workspace.id)).title,'Intelligence navigation fixture');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('button',{name:'All changes saved',exact:true}).waitFor();
  });
  await check('Exhausted daily capacity is visible and only an explicit settings change enables another job',async()=>{
    const used=(await api('/api/intelligence')).usage.jobs;await api('/api/intelligence/settings','PUT',{maxJobsPerDay:used});await nav().getByRole('button',{name:'Research',exact:true}).click();const research=page.getByRole('region',{name:'AI research and processing'});await until(async()=>await research.locator('.daily-capacity').textContent().then(text=>text.includes(used+' / '+used+' jobs used · 0 remaining')));assert.equal(await page.getByRole('button',{name:'Classify existing catalogue',exact:true}).isDisabled(),true);assert.equal((await api('/api/intelligence')).settings.maxJobsPerDay,used);await research.getByRole('button',{name:'Review job limit',exact:true}).click();await page.getByRole('region',{name:'Provider connections'}).locator('.daily-capacity.exhausted').waitFor();assert.equal(await page.getByRole('spinbutton',{name:'Jobs per day',exact:true}).inputValue(),String(used));await until(async()=>await nav().getByRole('button',{name:'Connections',exact:true}).getAttribute('aria-current')==='page');await page.screenshot({path:join(evidence,'daily-limit-visible.png'),fullPage:true,animations:'disabled'});await page.getByRole('spinbutton',{name:'Jobs per day',exact:true}).fill(String(used+1));await page.getByRole('button',{name:'Save AI settings',exact:true}).click();await until(async()=>(await api('/api/intelligence')).settings.maxJobsPerDay===used+1);await nav().getByRole('button',{name:'Research',exact:true}).click();await until(async()=>await research.locator('.daily-capacity').textContent().then(text=>text.includes('1 remaining')));assert.equal(await page.getByRole('button',{name:'Classify existing catalogue',exact:true}).isEnabled(),true);assert.equal((await jobs()).length,used,'Viewing limits must not start work');
  });
  await check('Removing the Jev connection is reflected after reload and narrow pages do not overflow',async()=>{
    await nav().getByRole('button',{name:'Connections',exact:true}).click();await page.getByRole('button',{name:'Remove Jev key',exact:true}).click();await page.getByText('Key required',{exact:true}).waitFor();await page.reload();await page.getByText('Key required',{exact:true}).waitFor();assert.equal((await api('/api/intelligence')).connections.jev.configured,false);await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(evidence,'connections-mobile.png'),fullPage:true});let sizes=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(sizes.width<=sizes.viewport+2,JSON.stringify(sizes));await nav().getByRole('button',{name:'Research',exact:true}).click();await until(async()=>await nav().getByRole('button',{name:'Research',exact:true}).getAttribute('aria-current')==='page');await page.screenshot({path:join(evidence,'ai-research-mobile.png'),fullPage:true,animations:'disabled'});sizes=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(sizes.width<=sizes.viewport+2,JSON.stringify(sizes));assert.deepEqual(pageErrors,[]);
  });
  report.result='PASS';report.providerCalls={classification:classifyCalls,planning:planCalls};report.usage=(await api('/api/intelligence')).usage;
}catch(error){report.result='FAIL';report.error=error.stack;console.error(error.stack);if(page)await page.screenshot({path:join(evidence,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();await browser?.close();await app?.close();const target=resolve(directory);assert.ok(target.startsWith(resolve(tmpdir())+'\\')||target.startsWith(resolve(tmpdir())+'/'));await rm(target,{recursive:true,force:true});await writeFile(join(evidence,'intelligence-e2e.json'),JSON.stringify(report,null,2));}
