import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,mkdir,writeFile,rm,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {startServer} from '../src/server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dir=path.resolve(root,process.env.GLASSES_EVIDENCE_DIR||'evidence/site-onboarding-2026-09-29/onboarding-browser');await mkdir(dir,{recursive:true});
const tempRoot=await realpath(tmpdir()),dataDir=await mkdtemp(path.join(tempRoot,'glasses-consent-ui-'));
const raw=await readFile(path.join(root,'catalogue/catalogue.json'),'utf8').catch(()=>readFile(path.join(root,'public-site/public/glasses/catalogue.json'),'utf8')),pack=JSON.parse(raw);
let calls=0,failNext=false,app,browser,page,token;const errors=[];
const report={at:new Date().toISOString(),scope:'Isolated database and synthetic HTTP transport for the exact retained public pack. No external catalogue/model requests.',checks:[]};
const providers={status:async()=>({}),classify:async()=>{throw Error('Inference forbidden');},plan:async()=>{throw Error('Inference forbidden');},rank:async()=>{throw Error('Inference forbidden');}};
async function start(){app=await startServer({port:0,dataDir,seed:false,autoScout:false,providers,catalogueFetcher:async(url,opts)=>{calls++;assert.equal(url,'https://lcfr.ai/glasses/catalogue.json');assert.equal(opts.redirect,'error');if(failNext){failNext=false;return new Response('Unavailable',{status:503});}return new Response(raw,{headers:{'Content-Type':'application/json'}});}});({token}=await(await fetch(app.url+'/api/session')).json());}
async function get(route){const r=await fetch(app.url+route,{headers:{'X-Glasses-Token':token}});assert.ok(r.ok);return r.json();}
async function check(name,fn){try{await fn();report.checks.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){report.checks.push({name,status:'FAIL',error:e.stack});await page.screenshot({path:path.join(dir,'failure-'+report.checks.length+'.png'),fullPage:true}).catch(()=>{});throw e;}}
try{
 await start();browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(app.url);
 await check('First launch asks clearly and does not fetch before a choice',async()=>{await page.getByRole('heading',{name:'Start with the shared catalogue?',exact:true}).waitFor();assert.equal(calls,0);assert.equal((await get('/api/onboarding')).onboarding.choice,'pending');assert.equal((await get('/api/catalog')).items.length,0);await page.screenshot({path:path.join(dir,'first-run-desktop.png'),fullPage:true});});
 await check('Declining is remembered across reload and still makes zero shared requests',async()=>{await page.getByRole('button',{name:'No thanks, start my own',exact:true}).click();await page.locator('.shared-catalogue-setup').waitFor({state:'hidden'});await page.reload();await page.getByRole('searchbox',{name:'Search catalogue',exact:true}).waitFor();assert.equal((await get('/api/onboarding')).onboarding.choice,'decline');assert.equal(await page.locator('.shared-catalogue-setup').count(),0);assert.equal(calls,0);});
 await check('An explicit later import populates the actual catalogue and shows its receipt',async()=>{await page.getByRole('button',{name:'Shared catalogue',exact:true}).click();await page.getByRole('button',{name:'Import latest catalogue',exact:true}).click();await page.getByRole('heading',{name:'Your shared catalogue is ready.',exact:true}).waitFor();assert.equal(calls,1);const state=(await get('/api/onboarding')).onboarding;assert.equal(state.lastSuccess.snapshot.contentHash,pack.contentHash);assert.equal(state.lastSuccess.snapshot.counts.total,pack.items.length);assert.ok((await page.locator('.shared-catalogue-receipt').innerText()).includes(pack.items.length.toLocaleString('en')));await page.getByRole('button',{name:/Inspect /}).first().waitFor();await page.screenshot({path:path.join(dir,'approved-import.png'),fullPage:true});});
 await check('Failed refresh preserves the previous pack and offers an explicit retry',async()=>{failNext=true;await page.getByRole('button',{name:'Import latest catalogue',exact:true}).click();await page.getByRole('heading',{name:'The shared catalogue could not be imported.',exact:true}).waitFor();assert.match(await page.getByRole('alert').innerText(),/503/);assert.equal(calls,2);assert.equal((await get('/api/onboarding')).onboarding.lastSuccess.snapshot.contentHash,pack.contentHash);assert.equal((await get('/api/status')).counts.total,pack.items.length);await page.getByRole('button',{name:'Retry catalogue import',exact:true}).click();await page.getByRole('heading',{name:'Your shared catalogue is ready.',exact:true}).waitFor();assert.equal(calls,3);await page.getByRole('button',{name:'Close catalogue setup',exact:true}).click();});
 await check('Restart preserves consent and never refreshes automatically',async()=>{await app.close();await start();await page.goto(app.url);await page.getByRole('searchbox',{name:'Search catalogue',exact:true}).waitFor();assert.equal((await get('/api/onboarding')).onboarding.status,'ready');assert.equal(calls,3);assert.equal(await page.locator('.shared-catalogue-setup').count(),0);});
 await check('Catalogue setup stays reachable and readable at320px',async()=>{await page.setViewportSize({width:320,height:844});await page.getByRole('button',{name:'Shared catalogue',exact:true}).click();await page.getByRole('heading',{name:'Your shared catalogue is ready.',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Close catalogue setup',exact:true}).focus();await page.keyboard.press('Enter');await page.locator('.shared-catalogue-setup').waitFor({state:'hidden'});await page.getByRole('button',{name:'Shared catalogue',exact:true}).click();await page.screenshot({path:path.join(dir,'setup-mobile.png'),fullPage:true});});
 await check('No runtime errors or unintended shared requests',async()=>{assert.deepEqual(errors,[]);assert.equal(calls,3);});
 report.status='PASS';
}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;console.error(e.message);}
finally{report.fetches=calls;report.errors=errors;await browser?.close();await app?.close();await writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2)+'\n');const resolved=await realpath(dataDir);if(path.dirname(resolved)!==tempRoot||!path.basename(resolved).startsWith('glasses-consent-ui-'))throw Error('Unsafe fixture cleanup');await rm(resolved,{recursive:true,force:true});}
