import React,{useCallback,useEffect,useRef,useState} from 'react';

const types=['tool','component','skill','agent','collection','reference'];
const labels={tool:'Tools',component:'Components',skill:'Skills',agent:'Agents',collection:'Collections',reference:'References'};
export function BulkDiscovery({active,request,onJobFindings}){
  const [snapshot,setSnapshot]=useState(null),[selected,setSelected]=useState(types),[name,setName]=useState('Balanced public catalogue scan'),[maximum,setMaximum]=useState(240),[sources,setSources]=useState(''),[refreshExisting,setRefreshExisting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null),[job,setJob]=useState(null),[autoId,setAutoId]=useState(null);
  const continuation=useRef(null),starting=useRef(null),activeRef=useRef(active),advance=useRef(null);
  activeRef.current=active;
  const stop=message=>{continuation.current=null;setAutoId(null);if(message)setNotice(message)};
  const load=useCallback(async()=>{const state=await request('/api/bulk-scans');setSnapshot(state);return state;},[request]);
  useEffect(()=>{if(!active){continuation.current=null;setAutoId(null);return;}let alive=true,polling=false;const poll=async()=>{if(polling)return;polling=true;try{const state=await request('/api/bulk-scans');if(alive){setSnapshot(state);await advance.current?.(state);}}catch(e){if(alive){continuation.current=null;setAutoId(null);setError(e.message);}}finally{polling=false}};poll();const timer=setInterval(poll,2500);const leave=()=>{continuation.current=null;setAutoId(null)};window.addEventListener('pagehide',leave);return()=>{alive=false;continuation.current=null;clearInterval(timer);window.removeEventListener('pagehide',leave)};},[active,request]);
  const post=(path,body)=>request(path,{method:'POST',body:JSON.stringify(body)});
  const perform=async(fn)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false)}};
  const errorKey=plan=>JSON.stringify(plan.errors||[]);
  const startBatch=async(plan,retryFailed=false)=>{
    const current=continuation.current;
    if(!activeRef.current||!current||current.id!==plan.id||starting.current)return;
    current.version=plan.version;
    const pending=request('/api/bulk-scans/'+plan.id+'/run',{method:'POST',body:JSON.stringify({maxSteps:100,retryFailed}),signal:AbortSignal.timeout(15000)});
    starting.current=pending;
    try{await pending;}catch(e){if(continuation.current===current){stop('Automatic continuation stopped. Inspect the error before resuming.');setError(e.message);}throw e;}finally{if(starting.current===pending)starting.current=null;}
  };
  advance.current=async state=>{
    const current=continuation.current;if(!current||!activeRef.current||starting.current)return;
    const plan=state.plans.find(row=>row.id===current.id);if(!plan){stop('The active scan is no longer available.');return;}
    if(!Number.isSafeInteger(plan.version)||plan.version<=current.version)return;
    if(plan.cancelRequested||plan.status==='cancelled'){stop('Scan cancelled. Resume only when you are ready.');return;}
    if(errorKey(plan)!==current.errors||plan.stats.failed>current.failed){stop('New source errors stopped automatic continuation. Inspect the receipts before resuming.');return;}
    if(['completed','bounded','partial','failed'].includes(plan.status)){stop(plan.status==='completed'?'Scan complete. Source evidence is ready to inspect.':'Scan stopped at its current limit or source outcome. Inspect the receipts before continuing.');return;}
    if(plan.status==='paused'&&plan.reason!=='batch-limit'){stop(plan.reason==='upstream-rate-limit'?'The upstream source rate limit paused this scan. Wait before explicitly resuming.':'Automatic continuation paused. Inspect the source receipts before resuming.');return;}
    // Only a newer durable checkpoint may authorize another batch. Overlapping
    // or late polls cannot submit the same checkpoint twice.
    if(plan.status==='paused'&&plan.reason==='batch-limit'&&!state.running&&Number.isSafeInteger(plan.version)&&plan.version>current.version)await startBatch(plan);
  };
  const resume=async plan=>{if(!activeRef.current){stop('Scan saved. Return to Research and choose Resume scan when ready.');return;}if(starting.current)return;continuation.current={id:plan.id,version:plan.version,errors:errorKey(plan),failed:plan.stats.failed};setAutoId(plan.id);setNotice('Scan continuing automatically while this Research view stays open. Each batch is limited to 100 steps; classification remains separate.');await startBatch(plan,plan.status==='partial');};
  const cancel=async plan=>{stop('Stopping this scan. No further batches will start.');const pending=starting.current;if(pending)await pending.catch(()=>{});await post('/api/bulk-scans/'+plan.id+'/cancel',{});};
  const create=event=>{event.preventDefault();perform(async()=>{const lanes=sources.trim()?JSON.parse(sources):snapshot.defaults.filter(lane=>selected.includes(lane.resourceType));const {plan}=await post('/api/bulk-scans',{name,maxCandidates:Number(maximum),refreshExisting,lanes});await resume(plan);});};
  const read=async(id,offset=0)=>{const response=await request('/api/bulk-scans/'+id+'?offset='+offset+'&limit=30');setDetail(response.plan);return response.plan;};
  const classify=()=>perform(async()=>{const ids=[...new Set((detail.entries||[]).filter(entry=>['added','updated'].includes(entry.status)).map(entry=>entry.candidateId).filter(Boolean))].slice(0,30);if(!ids.length)throw Error('This page has no newly admitted IDs to classify.');const response=await post('/api/intelligence/jobs',{type:'classify',candidateIds:ids});setJob(response.job);setNotice('Classification queued under your saved provider and dollar limits. Results appear in AI job history.');});
  return <section className="bulk-discovery" aria-label="Bulk discovery"><div className="section-heading"><div><h2>Bulk discovery</h2><p className="small-copy">Find reusable work across six resource types. Public sources are scanned without model calls; classify the admitted results when ready.</p></div></div>
    {error&&<p role="alert" className="intelligence-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <form onSubmit={create}><div className="settings-grid"><label className="field">Scan name<input value={name} maxLength={100} required onChange={e=>setName(e.target.value)}/></label><label className="field">Candidate limit<input aria-label="Bulk candidate limit" type="number" min={1} max={2000} required value={maximum} onChange={e=>setMaximum(e.target.value)}/></label></div><fieldset><legend>Resource lanes</legend><div className="automation-options">{types.map(type=><label className="checkbox-label" key={type}><input type="checkbox" checked={selected.includes(type)} onChange={e=>setSelected(e.target.checked?[...selected,type]:selected.filter(value=>value!==type))}/>{labels[type]}</label>)}</div></fieldset><p className="small-copy">Tools get the largest share. GitHub searches run from most to least stars; registry providers are interleaved. Skills and agents require actual source files and a verified scoped licence. Unsupported sources stay visible for review.</p>
      <label className="checkbox-label"><input type="checkbox" checked={refreshExisting} onChange={event=>setRefreshExisting(event.target.checked)}/>Refresh existing sources</label><p className="small-copy">Revisit known entries for newer source evidence and descriptions. Model classification is still a separate action.</p>
      <details><summary>Custom source lanes</summary><p className="small-copy">Edit the JSON to add GitHub queries, public owner/repository guidance sources or reference URLs. Changes apply to the next scan.</p><button type="button" className="button" onClick={()=>setSources(JSON.stringify(snapshot?.defaults||[],null,2))}>Load default sources</button><label className="field">Source lanes JSON<textarea aria-label="Source lanes JSON" rows={12} value={sources} onChange={e=>setSources(e.target.value)} placeholder="Leave blank to use selected default lanes"/></label></details>
      <button className="button primary" disabled={busy||!snapshot||snapshot.running||!!autoId||!selected.length}>Start bulk scan</button><p className="small-copy">Keep this Research view open to continue automatically. Leaving it or closing the browser stops continuation after the current bounded batch. Rate limits and errors pause the scan for your review.</p></form>
    <div className="ai-jobs">{snapshot?.plans.map(plan=><article className="ai-job" key={plan.id}><div className="heading-row"><h3>{plan.name}</h3><span className="pill">{plan.status}{autoId===plan.id?' · auto-continuing':''}</span></div><p>{plan.stats.added} added · {plan.stats.updated} updated · {plan.stats.existing} already catalogued · {plan.stats.reviewRequired} for review · {plan.stats.failed} failed</p><p className="small-copy">{plan.stats.attempted}/{plan.maxCandidates} candidates · {plan.stats.pages}/{plan.maxPages} source pages{plan.refreshExisting?' · refreshing known sources':''}</p><div className="tag-list">{plan.lanes.map(lane=><span className="pill" key={lane.resourceType}>{labels[lane.resourceType]} {lane.attempted}/{lane.limit}</span>)}</div>{plan.reason&&<p className="small-copy">{plan.reason}</p>}<div className="plan-actions"><button className="button" disabled={busy} onClick={()=>perform(()=>read(plan.id))}>View source receipts</button>{plan.status==='running'||autoId===plan.id?<button className="button" disabled={busy} onClick={()=>perform(()=>cancel(plan))}>Cancel scan</button>:<button className="button" disabled={busy||snapshot.running||!!autoId||['completed','bounded'].includes(plan.status)} onClick={()=>perform(()=>resume(plan))}>Resume scan</button>}</div></article>)}</div>
    {detail&&<div className="ai-job" aria-label="Bulk source receipts"><h3>{detail.name} — source receipts</h3><p className="small-copy">Requested lane and admission outcome are separate. “For review” does not mean a skill or agent was admitted.</p><ul>{detail.entries.map((entry,index)=><li key={index}><a href={entry.url} target="_blank" rel="noreferrer">{entry.name||entry.url}</a> · {labels[entry.lane]} · {entry.status}{entry.reason&&<p>{entry.reason}</p>}{entry.error&&<p>{entry.error}</p>}</li>)}</ul><div className="plan-actions"><button className="button" disabled={busy} onClick={classify}>Classify new results on this page</button>{detail.nextOffset!==null&&<button className="button" disabled={busy} onClick={()=>perform(()=>read(detail.id,detail.nextOffset))}>Next receipts</button>}<button className="button" onClick={()=>setDetail(null)}>Close receipts</button>{job&&<button className="button" onClick={()=>onJobFindings(job)}>View classification findings</button>}</div></div>}
  </section>;
}
